backend:
  name: git-gateway

media_folder: static/img
public_folder: /img

collections:
  - name: "architecture"
    label: "Architecture"
    folder: "src/pages/products/architecture"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "single"}
      - {label: "Category", name: "category", widget: "hidden", default: "architecture"}
      - {label: "Název", name: "nazev", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      # - {label: "Cena v CZK", name: "cena", widget: "string"}
      # - {label: "Price in EUR", name: "price", widget: "string"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}

  - name: "fashion"
    label: "Fashion"
    folder: "src/pages/products/fashion"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "single"}
      - {label: "Category", name: "category", widget: "hidden", default: "fashion"}
      - {label: "Název", name: "nazev", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      # - {label: "Cena v CZK", name: "cena", widget: "string"}
      # - {label: "Price in EUR", name: "price", widget: "string"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}

  - name: "street"
    label: "Street"
    folder: "src/pages/products/street"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "single"}
      - {label: "Category", name: "category", widget: "hidden", default: "street"}
      - {label: "Název", name: "nazev", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      # - {label: "Cena v CZK", name: "cena", widget: "string"}
      # - {label: "Price in EUR", name: "price", widget: "string"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}

  - name: "product"
    label: "Product"
    folder: "src/pages/products/product"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "single"}
      - {label: "Category", name: "category", widget: "hidden", default: "architecture"}
      - {label: "Název", name: "nazev", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      # - {label: "Cena", name: "cena", widget: "string"}
      # - {label: "Price", name: "price", widget: "string"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}

  - name: "general"
    label: "Obecně"
    files:
      - file: "src/pages/categories/general.md"
        label: "Hlavní stránka"
        name: "frontpage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "setting"}
          - {label: "Category", name: "category", widget: "hidden", default: "general"}
          - {label: "Popis", name: "popis", widget: "text"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Úvodní fotka", name: "thumbnail", widget: "image"}
          - {label: "Facebook", name: "facebook", widget: "string"}
          - {label: "Instagram", name: "instagram", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Telefon", name: "phone", widget: "string"}
          - {label: "Objednávka", name: "objednavka", widget: "text"}
          - {label: "Order", name: "order", widget: "text"}
      - file: "src/pages/categories/architecture.md"
        label: "Architecture"
        name: "architecture-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
          - {label: "Category", name: "category", widget: "hidden", default: "architecture"}
          - {label: "Popis", name: "popis", widget: "text"}
          - {label: "Description", name: "description", widget: "text"}
      - file: "src/pages/categories/fashion.md"
        label: "Fashion"
        name: "fashion-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
          - {label: "Category", name: "category", widget: "hidden", default: "fashion"}
          - {label: "Popis", name: "popis", widget: "text"}
          - {label: "Description", name: "description", widget: "text"}
      - file: "src/pages/categories/street.md"
        label: "Street"
        name: "street-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
          - {label: "Category", name: "category", widget: "hidden", default: "street"}
          - {label: "Popis", name: "popis", widget: "text"}
          - {label: "Description", name: "description", widget: "text"}
      - file: "src/pages/categories/product.md"
        label: "Product"
        name: "product-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
          - {label: "Category", name: "category", widget: "hidden", default: "product"}
          - {label: "Popis", name: "popis", widget: "text"}
          - {label: "Description", name: "description", widget: "text"}
