backend:
  name: git-gateway

media_folder: static/img
public_folder: /img

collections:
  - name: "architecture"
    label: "Architecture"
    folder: "src/pages/products/mirror"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "single"}
      - {label: "Category", name: "category", widget: "hidden", default: "mirror"}
      - {label: "Název", name: "nazev", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cena v CZK", name: "cena", widget: "string"}
      - {label: "Price in EUR", name: "price", widget: "string"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}

  - name: "fashion"
    label: "Fashion"
    folder: "src/pages/products/photography"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "single"}
      - {label: "Category", name: "category", widget: "hidden", default: "photography"}
      - {label: "Název", name: "nazev", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cena v CZK", name: "cena", widget: "string"}
      - {label: "Price in EUR", name: "price", widget: "string"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}

  - name: "street"
    label: "Street"
    folder: "src/pages/products/jewellery"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "single"}
      - {label: "Category", name: "category", widget: "hidden", default: "jewellery"}
      - {label: "Název", name: "nazev", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cena v CZK", name: "cena", widget: "string"}
      - {label: "Price in EUR", name: "price", widget: "string"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}

  - name: "product"
    label: "Product"
    folder: "src/pages/products/glass"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "single"}
      - {label: "Category", name: "category", widget: "hidden", default: "mirror"}
      - {label: "Popisek", name: "title", widget: "string"}
      - {label: "Cena", name: "cena", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}

  - name: "general"
    label: "Obecně"
    files:
      - file: "src/pages/categories/general.md"
        label: "Hlavní stránka"
        name: "frontpage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "setting"}
          - {label: "Category", name: "category", widget: "hidden", default: "general"}
          - {label: "Popis", name: "popis", widget: "text"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Úvodní fotka", name: "thumbnail", widget: "image"}
          - {label: "Facebook", name: "facebook", widget: "string"}
          - {label: "Instagram", name: "instagram", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Telefon", name: "phone", widget: "string"}
          - {label: "Objednávka", name: "objednavka", widget: "text"}
          - {label: "Order", name: "order", widget: "text"}
      - file: "src/pages/categories/mirror.md"
        label: "Zrcadlo"
        name: "mirror-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
          - {label: "Category", name: "category", widget: "hidden", default: "mirror"}
          - {label: "Popis", name: "popis", widget: "text"}
          - {label: "Description", name: "description", widget: "text"}
      - file: "src/pages/categories/photography.md"
        label: "Fotka"
        name: "photography-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
          - {label: "Category", name: "category", widget: "hidden", default: "photography"}
          - {label: "Popis", name: "popis", widget: "text"}
          - {label: "Description", name: "description", widget: "text"}
      - file: "src/pages/categories/jewellery.md"
        label: "Šperk"
        name: "jewellery-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
          - {label: "Category", name: "category", widget: "hidden", default: "jewellery"}
          - {label: "Popis", name: "popis", widget: "text"}
          - {label: "Description", name: "description", widget: "text"}
      - file: "src/pages/categories/glass.md"
        label: "Sklo"
        name: "glass-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
          - {label: "Category", name: "category", widget: "hidden", default: "glass"}
          - {label: "Popis", name: "popis", widget: "text"}
          - {label: "Description", name: "description", widget: "text"}
